version: "2"

services:
  server:
    build: .
    volumes:
      - ./:/app
    ports:
      - 4001:8082
    env_file:
      - .env
    links:
      - database
      - redis
    command: ["npm", "start"]
  database:
    image: postgres:9.6-alpine
    ports:
      - 11544:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
  redis:
    image: redis
    container_name: cache
    ports:
      - 6377:6379

volumes:
  database-data: {}
