enum UserRolesEnum {
  ADMIN = 'Admin',
  DEVELOPER = 'DEVELOPER',
  DESIGNER = 'DESIGNER', 
  DATA_SCIENTIST = 'DATA SCIENTIST',
  TECHNICAL_AUDIT = 'TECHNICAL_AUDIT',
  FINANCIAL_ENGINEER = 'FINANCIAL ENGINEER'
}

export default UserRolesEnum;
