

@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json


##

// Login get the Access and Refresh token
POST  /api/auth/login HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
	"identificator" : "owner",
	"password" : "pass"
}


###


POST  /api/auth/refresh HTTP/1.1
Host: {{host}}
Content-Type: {{contentType}}

{
	"identificator": "ibra" ,
	"token" : "eyJhbGcieyJ1c2VybmFtZyI",
	"refreshToken" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhdG9yIjoiaWJyYSIsImlzT3duZXIiOnRydWUsInJvbGUiOiJTdXBlciBhZG1pbiIsImlhdCI6MTU3ODc4NjE1Nn0.CglfsAPBIaqXNuKnoJO4d35__XB66WESKPQield6BT4"
}
